<?php

namespace XP\TeamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MemberAvatarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberAvatarRepository extends EntityRepository
{
}
