xp_team:
    resource: "@XPTeamBundle/Controller/"
    type:     annotation
    prefix:   /

xp_team_admin:
    resource: "@XPTeamBundle/Controller/Admin/"
    type:     annotation
    prefix:   /admin/
